apiVersion: v1
kind: Service
metadata:
  namespace: datacentre
  labels:
    component: etcd
  name: etcd
spec:
  clusterIP: None
  selector:
    component: etcd
  ports:
  - name: api
    port: 2379
    targetPort: 2379
  - name: peer
    port: 2380
    targetPort: 2380
