apiVersion: v1
kind: Service
metadata:
  namespace: datacentre
  name: cassandra-worker
  labels:
    component: cassandra-worker
spec:
  type: ClusterIP
  selector:
    component: cassandra-worker
  ports:
  - port: 7000
    targetPort: 7000
    name: peer
  - port: 9160 
    targetPort: 9160
    name: rpc
  - port: 7199 
    targetPort: 7199
    name: jmx
  - port: 9042 
    targetPort: 9042
    name: cql
