apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  namespace: datacentre
  name: cassandra-worker
spec:
  serviceName: "cassandra-worker"
  podManagementPolicy: Parallel
  replicas: 3
  template:
    metadata:
      labels:
        component: cassandra-worker
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: cassandra-worker
        image: 172.31.78.217:5000/cassandra:v2
        command: ["/start-worker.sh"]
        env:
        - name: DSCV
          value: cassandra-master
        - name: NET_ID 
          valueFrom:
            configMapKeyRef:
              name: dc-config
              key: dc.net-id
        - name: CLUSTER_NAME
          valueFrom:
            configMapKeyRef:
              name: dc-config
              key: cassandra.cluster-name
        ports:
        - containerPort: 7000 
        - containerPort: 7199 
        - containerPort: 9042 
        - containerPort: 9160 
