apiVersion: apps/v1beta1
kind: StatefulSet 
metadata:
  namespace: datacentre
  name: cassandra-master
spec:
  serviceName: "cassandra-master"
  replicas: 1
  template:
    metadata:
      labels:
        component: cassandra-master
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: cassandra-master
        image: 172.31.78.217:5000/cassandra:v2
        command: ["/start-master.sh"]
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: CLUSTER_NAME
          valueFrom:
            configMapKeyRef:
              name: dc-config
              key: cassandra.cluster-name
        ports:
        - containerPort: 7000 
        - containerPort: 7199 
        - containerPort: 9042 
        - containerPort: 9160 
        volumeMounts:
        - name: gluster-volume
          mountPath: "/mnt"
      volumes:
      - name: gluster-volume
        persistentVolumeClaim:
          claimName: glusterfs-pvc
