apiVersion: v1
kind: Service
metadata:
  namespace: datacentre
  name: cassandra-master
  labels:
    component: cassandra-master
spec:
  clusterIP: None
  selector:
    component: cassandra-master
  ports:
  - port: 7000
    targetPort: 7000
    name: peer
  - port: 9160 
    targetPort: 9160
    name: rpc
  - port: 7199 
    targetPort: 7199
    name: jmx
  - port: 9042 
    targetPort: 9042
    name: cql
