kind: Deployment 
apiVersion: extensions/v1beta1 
metadata:
  namespace: datacentre
  name: spark-worker-controller
spec:
  replicas: 3
  template:
    metadata:
      labels:
        component: spark-worker
    spec:
      containers:
      - name: spark-worker
        image: 172.31.78.217:5000/spark:2.3.0
        command: ["/start-worker"]
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        ports:
        - containerPort: 8081
        resources:
          requests:
            cpu: 100m
      initContainers:
      - name: wait4master
        image: busybox
        command: ['sh', '-c', 'until nslookup $DSCV; do echo waiting for $DSCV; sleep 2; done;']
        env:
        - name: DSCV
          value: spark-master

