kind: Service
apiVersion: v1
metadata:
  namespace: datacentre
  name: spark-ui-proxy
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    component: spark-ui-proxy
  type: LoadBalancer
