kind: Deployment 
apiVersion: extensions/v1beta1 
metadata:
  namespace: datacentre
  name: spark-worker-controller
spec:
  replicas: 3
  template:
    metadata:
      labels:
        component: spark-worker
    spec:
      containers:
        - name: spark-worker
          image: 172.31.78.217:5000/spark
          command: ["/start-worker"]
          ports:
            - containerPort: 8081
          resources:
            requests:
              cpu: 100m

