apiVersion: v1
kind: Service
metadata:
  namespace: datacentre
  name: mysql-ndb
  labels:
    component: mysql-ndb
spec:
  clusterIP: None
  selector:
    component: mysql-ndb
  ports:
  - port: 1186 
    targetPort: 1186 
    name: peer 
  - port: 2202 
    targetPort: 9160
    name: ndbd 
