apiVersion: v1
kind: Service
metadata:
  namespace: datacentre
  name: mysql-mgm
  labels:
    component: mysql-mgm
spec:
  type: ClusterIP
  selector:
    component: mysql-mgm
  ports:
  - port: 1186 
    targetPort: 1186 
    name: peer 
  - port: 2202 
    targetPort: 2202 
    name: ndbd 
