kind: ConfigMap
apiVersion: v1
metadata:
  namespace: datacentre
  name: mysql-other-config
data:
  my.cnf: |-
    [mysqld]
    ndbcluster

    [mysql_cluster]
    ndb-connectstring={{ip.addr}}
  start-ndbd.sh: |-
    #!/bin/bash
    set -e
    INFO=$(getent hosts $DSCV)
    if [ -z "$INFO" ]; then
      echo "=== Cannot resolve the DNS entry for $DSCV. Has the service been created yet, and is SkyDNS functional?"
      echo "=== See http://kubernetes.io/v1.1/docs/admin/dns.html for more details on DNS integration."
      echo "=== Sleeping 10s before pod exit."
      sleep 10
      exit 0
    fi
    cp /etc/config/my.cnf /etc
    MGM=$(echo $INFO | awk -F ' ' '{print $1}')
    sed -i "s/{{ip.addr}}/${MGM}/g" /etc/my.cnf
    while true; do sleep 60; done
  start-sqld.sh: |-
    #!/bin/bash
    set -e
    INFO=$(getent hosts $DSCV)
    if [ -z "$INFO" ]; then
      echo "=== Cannot resolve the DNS entry for $DSCV. Has the service been created yet, and is SkyDNS functional?"
      echo "=== See http://kubernetes.io/v1.1/docs/admin/dns.html for more details on DNS integration."
      echo "=== Sleeping 10s before pod exit."
      sleep 10
      exit 0
    fi
    cp /etc/config/my.cnf /etc
    MGM=$(echo $INFO | awk -F ' ' '{print $1}')
    sed -i "s/{{ip.addr}}/${MGM}/g" /etc/my.cnf
    while true; do sleep 60; done
