kind: Deployment 
apiVersion: extensions/v1beta1 
metadata:
  namespace: datacentre
  name: zeppelin-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: zeppelin
    spec:
      containers:
        - name: zeppelin
          image: 172.31.78.217:5000/zeppelin:0.7.3
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
