apiVersion: v1
kind: Endpoints
metadata:
  namespace: datacentre
  name: glusterfs-cluster
subsets:
- addresses:
  - ip: 172.31.78.215
  - ip: 172.31.78.216
  - ip: 172.31.78.217
  ports:
  - port: 1990
    protocol: TCP
