apiVersion: v1
kind: Service
metadata:
  namespace: datacentre
  labels:
    component: zookeeper 
  name: zookeeper
spec:
  clusterIP: None 
  selector:
    component: zookeeper
  ports:
  - port: 2181 
    targetPort: 2181 
    name: client
  - port: 2888
    targetPort: 2888 
    name: peer
  - port: 3888
    targetPort: 3888 
    name: leader-election
