apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  namespace: datacentre
  name: zookeeper
spec:
  serviceName: "zookeeper"
  podManagementPolicy: Parallel
  replicas: 3
  template:
    metadata:
      labels:
        component: zookeeper
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: zookeeper
        image: 172.31.78.217:5000/zookeeper:v1
        command: ["/entrypoint.sh"]
        env:
        - name: N_NODES
          value: "3"
        - name: DSCV
          value: "zookeeper"
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: TRIES
          valueFrom:
            configMapKeyRef:
              name: dc-config
              key: tries
        volumeMounts:
        - name: gluster-volume
          mountPath: "/mnt"
      volumes:
      - name: gluster-volume
        persistentVolumeClaim:
          claimName: glusterfs-pvc
