apiVersion: apps/v1beta1
kind: StatefulSet 
metadata:
  namespace: datacentre
  name: redis-master
spec:
  serviceName: "redis-master"
  replicas: 1
  template:
    metadata:
      labels:
        component: redis-master
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: redis-master
        image: 172.31.78.217:5000/redis:4.0.7
        command: ["/etc/scripts/entrypoint.active-backup.sh"]
        env:
        - name: DSCV
          value: redis-master
        - name: ROLE
          value: MASTER 
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: TRIES
          valueFrom:
            configMapKeyRef:
              name: dc-config
              key: tries 
        ports:
        - containerPort: 6379
        - containerPort: 16379
        volumeMounts:
        - name: "entrypoint-scripts"
          mountPath: "/etc/scripts"
          readOnly: true
      volumes:
      - name: entrypoint-scripts
        configMap:
          name: redis-entrypoint-scripts 
          defaultMode: 0755
