apiVersion: v1
kind: Service
metadata:
  namespace: datacentre
  labels:
    svc: redis-master
  name: redis-master
spec:
  selector:
    component: redis-master
  ports:
  - port: 6379 
    targetPort: 6379
